### ISSUE TITLE
Demo beautification

### ISSUE THREAD

**Issue by jeromesimeon** [querycert/qcert#47]
- [x] Ensure text for tabs and ILs fits in boxes (better fonts? better sizes? better centering?)
- [x] Ensure consistent fonts throughout the demo (e.g., text boxes vs tabs)
- [x] Better colors?
- [x] Add logo?

**Comment by jeromesimeon** [comment]
Hi Avi, I assign this to you for now in case you have some time (and as I know you're doing some refactoring it might be something easy to squeeze in). None of it is fundamental or required, but just some thoughts/suggestions.

**Comment by joshuaauerbachwatson** [comment]
Just noting:

I did step one in our planned overall reorganization of the demo.   The compile and execute tabs are now html based rather than canvas based (since they include input areas).   Results are displayed in a readonly textarea rather than using a fabric Text object.   As a consequence, lines wrap and there are only vertical scroll bars.  

This doesn't necessarily completely address the first work item but I think it makes the text a little more readable and it might be good for @jeromesimeon to have a look to see what's most in need of further improvement before @shinnar plunges in.

**Comment by jeromesimeon** [comment]
This has been mostly done. Additional improvements for the demo can be raised as additional issues.
