### ISSUE TITLE
Intermediate output files should not be put in the source target directory

### ISSUE THREAD

**Issue by shinnar** [querycert/qcert#81]
When using emit-all, the generated intermediate files should be placed in the -dir-target folder, not adjacent to the source file.

Optionally, we could add another config, -dir-debug, which enables more fine grained control.  If not specified, it should default to -dir-target.  If that is not specified, it can default to being next to the target.

**Comment by mandel** [comment]
There is the option `-dir` that specify the directory for all emitted files. The option `-dir-target` specifies the directory only for the target file. So if you use `-dir` instead of `-dir-target` you should have the behavior that you expect.

@shinnar Do you think that this behavior should be changed?

**Comment by shinnar** [comment]
@mandel No, that behaviour is perfect, I just need to learn how to read :-/
